name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    
    - name: Build
      run: |
        docker build . -t builder
        docker run -v ${PWD}/:/opt/mount --rm --entrypoint cp builder /usr/bin/sing-box /opt/mount/sing-box
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.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 }}
        file: ./sing-box
        asset_name: sing-box
        tag: ${{ github.ref }}
        overwrite: true
